---
title: "R Notebook"
output:
  html_notebook: default
  html_document:
    df_print: paged
  pdf_document: default
---


```{r}
# install.packages("OpenImageR") 
# install.packages("dplyr")
# install.packages("iterators")
# install.packages("nnet")
# install.packages("reshape2")
# install.packages("ggplot2")
# install.packages("caret")
# install.packages("glmnet")
# install.packages("e1071")
# install.packages("factoextra")

```


```{r warning=FALSE}
options(warn=-1)#Warning off

library(OpenImageR) 
library(dplyr)
library(iterators)
library(nnet)
library(reshape2)
library(ggplot2)
library(glmnet)
library(e1071)
library(factoextra)
library(grid)
library(gridExtra)
library(stats)


production = FALSE
if(production == TRUE){
  prod.number_of_repeats = 10
  prod.sample_size = 5000
}else{
  prod.number_of_repeats = 2
  prod.sample_size = 250
}

accs = c()

options(warn=0)#Warning back on
```
```{r}
mnist.dat <- read.csv("mnist.csv")
pixels_data = mnist.dat[,-1]
scaled_pixels_data = scale(pixels_data)
scaled_pixels_data[is.na(scaled_pixels_data)] = 0 #Replacing NaN with 0
mnist.dat$label = as.factor(mnist.dat$label)
```
```{r}
show_image_from_data = function(data, row) {
  sample_image = t(matrix(as.numeric(data[row,-1]),nrow=28,ncol=28,byrow=T)[c(28:1),,drop = FALSE])
  return (image(sample_image, axes = FALSE, col = grey(seq(0, 1, length = 256)), asp=1))
}
show_image_data = function(actual_digit) {
  return (t(matrix(as.numeric(actual_digit),nrow=28,ncol=28,byrow=T))[,c(28:1),drop = FALSE])
}

edge_detect = function(normal_digit){
  digit_example = show_image_data(normal_digit)
  detect_image = edge_detection(digit_example,  method = 'Scharr', conv_mode = 'same')
  return (t(detect_image))
}

plot_confusion_matrix = function(confmat){
  melted_confmat <- melt(as.matrix(confmat))
  return (ggplot(data =  melted_confmat, mapping = aes(x = Var1, y = predicted)) +
    geom_tile(aes(fill = value), colour = "white") +
    geom_text(aes(label = sprintf("%1.0f", value)), vjust = 1) +
    scale_fill_gradient(low = "blue", high = "red") +
    theme_bw() + theme(legend.position = "none") + 
    scale_x_discrete(name="Actual Digit", limits=0:9) + scale_y_discrete(name="Predicted Digit", limits=0:9))
}

show_image_from_data(mnist.dat, 1)  

```
```{r}
mnist.summary = data.frame(t(sapply( pixels_data , function(x) cbind(mean = mean(x) ,
                                  sd = sd(x) ,
                                  median = median(x) ,
                                  minimum = min(x) ,
                                  maximum = max(x) ,
                                  s.size = length(x)))))
colnames(mnist.summary) = c("mean","sd","median","minimum","maximum","size")
head(mnist.summary[mnist.summary$sd==0,])

```

```{r}
indices_of_useless_features = which(mnist.summary$sd == 0)
actual_digit_strict = mnist.dat[2,-1]
actual_digit_strict[,indices_of_useless_features] = 125
digit_example_strict = show_image_data(actual_digit_strict)
image(digit_example_strict, axes = FALSE, col = grey(seq(0, 1, length = 256)), asp=1)
```
```{r}
indices_of_useless_features = which(mnist.summary$sd < 1)
actual_digit = mnist.dat[2,-1]
actual_digit[,indices_of_useless_features] = 125
digit_example = show_image_data(actual_digit)
image(digit_example, axes = FALSE, col = grey(seq(0, 1, length = 256)), asp=1)
```
```{r}
# standard_deviations_prepared_for_image = matrix(mnist.summary$sd/max(mnist.summary$sd), nrow=28, ncol=28, byrow=TRUE)
# meaningfullness_image = rasterGrob(standard_deviations_prepared_for_image)
# meaningfullness_image_strict = rasterGrob(digit_example_strict/255)
# meaningfullness_image_soft = rasterGrob(digit_example/255)
# 
# png('figures/discarded_pixels.png')
# grid.arrange(meaningfullness_image_strict, meaningfullness_image_soft, ncol=2, clip=TRUE, respect=FALSE, heights=c(1,0))
# dev.off()
# 
# png('figures/meaningless.png')
# image(standard_deviations_prepared_for_image, axes=FALSE, col = grey(seq(0, 1, length = 256)), asp=1)
# dev.off
```

```{r}
label_distribution = table(mnist.dat[,1]) 
barplot(label_distribution, main="Digits in dataset")
```
```{r}
expected_accuracy_on_majority_label_classification = label_distribution[2] / sum(label_distribution)
accs = c(accs, expected_accuracy_on_majority_label_classification)
sprintf("Accuracy if 1 was predicted for all labels: %.2f %%", expected_accuracy_on_majority_label_classification * 100)
```

```{r}
actual_digit = mnist.dat[450,-1]
indices_of_useful_features = which(actual_digit < 248)
actual_digit[,indices_of_useful_features] = 0
digit_example = show_image_data(actual_digit)
image(digit_example, axes = FALSE, col = grey(seq(0, 1, length = 256)), asp=1)
```

```{r}
hist(as.numeric(actual_digit), main="Frequency of pixels values", xlab="Pixel Value", ylab="Frequency")

```

```{r}
hist.data = hist(as.matrix(mnist.dat[,-1]), breaks=32, main="Frequency of pixels values", xlab="Pixel Value", ylab="Frequency")
hist.data$counts = log10(hist.data$counts)
plot(hist.data, main="Frequency of scaled pixels values", xlab="Pixel Value", ylab="Frequency")
axis(side=1, at=seq(0, 256, 8))
```

```{r}
cleaned_images = t(apply(pixels_data, MARGIN = 1, FUN=function(x) replace(x, which(x < 5), 0)))
image_density = apply(cleaned_images, MARGIN=1, FUN=function(x) sum(x))
image_density_per_pixel = apply(data.frame(image_density), MARGIN=1, FUN=function(x) sum(x)/784)

pca_model = prcomp(scaled_pixels_data[,-indices_of_useless_features])
principal_components = as.matrix(pca_model$x)

edge_detected_images = t(apply(cleaned_images, MARGIN=1, FUN=edge_detect))
image_density_edge_detected = apply(edge_detected_images, MARGIN=1, FUN=function(x) sum(x))

data = cbind.data.frame(density=image_density, 
                        density_per_pixel=scale(image_density_per_pixel), 
                        scaled_density = scale(image_density), 
                        label=mnist.dat$label)


data2 = cbind.data.frame(log_dens=scale(log(image_density_per_pixel)), 
                        sqrt_dens=scale(sqrt(image_density_per_pixel)), 
                        sin_dens=scale(sin(image_density_per_pixel)), 
                        tanh_dens=tanh(scale(image_density_per_pixel)),  #TODO: Explain why scale after
                        scaled_density = scale(image_density),
                        squared_dens=scale(image_density^2),
                        label=mnist.dat$label)




data3 = cbind.data.frame(scaled_density = scale(image_density),
                         first_pca = scale(principal_components[,1]),
                        label=mnist.dat$label)




data4 = cbind.data.frame(density=image_density, 
                        scaled_density=scale(image_density), 
                        scaled_density_edge_detected = scale(image_density_edge_detected), 
                        label=mnist.dat$label)


data5 = cbind.data.frame(scaled_density = scale(image_density),
                         first_pca = scale(principal_components[,1]),
                         second_pca = scale(principal_components[,2]),
                         label=mnist.dat$label)

head(data)
head(data2)
head(data3)
head(data4)
head(data5)
```
```{r}
data_for_boxplots = cbind.data.frame(density=image_density, 
                        label=mnist.dat$label)
boxplot(density~label,sample_n(data_for_boxplots, 5000))
```

```{r}
summary_per_digit = rbind.data.frame(tapply(data$density_per_pixel, data$label,  function(x) cbind(mean = mean(x) ,
                                  sd = sd(x) ,
                                  median = median(x) ,
                                  minimum = min(x) ,
                                  maximum = max(x),
                                  s.size = length(x))
                           ))
rownames(summary_per_digit) = c("mean","sd","median","minimum","maximum","size") 
data.frame(t(summary_per_digit))
```

#Distance Matrix Density
```{r}
distance_matrix = dist(t(summary_per_digit[c("mean","sd"),]))
melted_cormat = melt(ifelse(!is.finite(log(as.matrix(distance_matrix))+4), 0, log(as.matrix(distance_matrix))+4))

ggplot(data =  melted_cormat, mapping = aes(x = Var1, y = Var2)) +
  geom_tile(aes(fill = value), colour = "white") +
  geom_text(aes(label = sprintf("%1.0f", value)), vjust = 1) +
  scale_fill_gradient(low = "blue", high = "red") +
  theme_bw() + theme(legend.position = "right") + 
  scale_x_discrete(name="Digit") + scale_y_discrete(name="Digit")
```

#Logit only Density

```{r}
density_model_density_only = multinom(label ~ scaled_density, data2, maxit=1000)
predicted = predict(density_model_density_only, data)
confmat = table(data$label, predicted)

acc = sum(diag(confmat))/sum(confmat)

acc_per_clas = as.data.frame(diag(confmat)/label_distribution )

precision = as.data.frame(diag(confmat) / rowSums(confmat)) # Precision

recall = as.data.frame(diag(confmat) / colSums(confmat)) # Recall

recall[is.na(recall)] = 0

overall = cbind.data.frame(Precision=precision, Recall=recall)
colnames(overall) = c("Precision", "Recall")

overall
acc
```

```{r}
melted_confmat <- melt(as.matrix(confmat))
ggplot(data =  melted_confmat, mapping = aes(x = Var1, y = predicted)) +
  geom_tile(aes(fill = value), colour = "white") +
  geom_text(aes(label = sprintf("%1.0f", value)), vjust = 1) +
  scale_fill_gradient(low = "blue", high = "red") +
  theme_bw() + theme(legend.position = "none") + 
  scale_x_discrete(name="Actual Digit", limits=0:9) + scale_y_discrete(name="Predicted Digit", limits=0:9)
```

#Logit Density + Squared Density

```{r}
density_model_density_and_squared = multinom(label ~ scaled_density + squared_dens, data2, maxit=1000)
predicted = predict(density_model_density_and_squared, data2)
confmat = table(data2$label, predicted)
confmat
accs = c(accs, sum(diag(confmat))/sum(confmat))
```

```{r}
melted_confmat <- melt(as.matrix(confmat))
ggplot(data =  melted_confmat, mapping = aes(x = Var1, y = predicted)) +
  geom_tile(aes(fill = value), colour = "white") +
  geom_text(aes(label = sprintf("%1.0f", value)), vjust = 1) +
  scale_fill_gradient(low = "blue", high = "red") +
  theme_bw() + theme(legend.position = "none") + 
  scale_x_discrete(name="Actual Digit", limits=0:9) + scale_y_discrete(name="Predicted Digit", limits=0:9)
```

#Logit Edge Detection

```{r}
actual_digit = edge_detected_images[445,]
image(matrix(actual_digit, nrow=28,ncol=28,byrow=T), axes = FALSE, col = grey(seq(0, 1, length = 256)), asp=1)
```

```{r}
density_model_edge_detected = multinom(label ~ scaled_density_edge_detected, data4, maxit=1000)
predicted = predict(density_model_edge_detected, data4)
confmat = table(data4$label, predicted)
accs = c(accs, sum(diag(confmat))/sum(confmat))
```

```{r}
melted_confmat <- melt(as.matrix(confmat))
ggplot(data =  melted_confmat, mapping = aes(x = Var1, y = predicted)) +
  geom_tile(aes(fill = value), colour = "white") +
  geom_text(aes(label = sprintf("%1.0f", value)), vjust = 1) +
  scale_fill_gradient(low = "blue", high = "red") +
  theme_bw() + theme(legend.position = "none") + 
  scale_x_discrete(name="Actual Digit", limits=0:9) + scale_y_discrete(name="Predicted Digit", limits=0:9)
```

#Logit Principle Component

```{r}
density_model_PCA = multinom(label ~ first_pca, data5, maxit=1000)

predicted = predict(density_model_PCA, data5)
confmat = table(data5$label, predicted)
accs = c(accs, sum(diag(confmat))/sum(confmat))
```

```{r}
melted_confmat <- melt(as.matrix(confmat))
ggplot(data =  melted_confmat, mapping = aes(x = Var1, y = predicted)) +
  geom_tile(aes(fill = value), colour = "white") +
  geom_text(aes(label = sprintf("%1.0f", value)), vjust = 1) +
  scale_fill_gradient(low = "blue", high = "red") +
  theme_bw() + theme(legend.position = "none") + 
  scale_x_discrete(name="Actual Digit", limits=0:9) + scale_y_discrete(name="Predicted Digit", limits=0:9)
```

#Principles components Analysis, Distance Matrix and BoxPlots

```{r}
summary_per_digit = rbind.data.frame(tapply(principal_components[,1]/784, mnist.dat$label,  function(x) cbind(mean = mean(x) ,
                                  sd = sd(x) ,
                                  median = median(x) ,
                                  minimum = min(x) ,
                                  maximum = max(x),
                                  s.size = length(x))
                           ))
rownames(summary_per_digit) = c("mean","sd","median","minimum","maximum","size") 
data.frame(t(summary_per_digit))
```

```{r}
cormat = dist(t(summary_per_digit[c("mean","sd"),]))
melted_cormat <- melt(ifelse(!is.finite(log(as.matrix(cormat))), 0, log(as.matrix(cormat))+4))
ggplot(data = melted_cormat, aes(x=Var1, y=Var2, fill=value)) + geom_tile()


ggplot(data =  melted_cormat, mapping = aes(x = Var1, y = Var2)) +
  geom_tile(aes(fill = value), colour = "white") +
  geom_text(aes(label = sprintf("%1.0f", value)), vjust = 1) +
  scale_fill_gradient(low = "blue", high = "red") +
  theme_bw() + theme(legend.position = "right") + 
  scale_x_discrete(name="Digit") + scale_y_discrete(name="Digit")
```

#First and Second PC 

```{r}
data_for_boxplots = cbind.data.frame(pca=principal_components[,1], label = mnist.dat$label)
boxplot(pca~label, sample_n(data_for_boxplots, 5000), main="First PC", xlab="Classes", ylab="PC value")

data_for_boxplots = cbind.data.frame(pca=principal_components[,2], label = mnist.dat$label)
boxplot(pca~label, sample_n(data_for_boxplots, 5000), main="Second PC", xlab="Classes", ylab="PC value")
```

```{r}
density_model_first_second_PC = multinom(label ~ first_pca + scaled_density, data5, maxit=1000)
predicted = predict(density_model_first_second_PC, data5)
confmat = table(data5$label, predicted)
accs = c(accs, sum(diag(confmat))/sum(confmat))
```

```{r}
melted_confmat <- melt(as.matrix(confmat))
ggplot(data =  melted_confmat, mapping = aes(x = Var1, y = predicted)) +
  geom_tile(aes(fill = value), colour = "white") +
  geom_text(aes(label = sprintf("%1.0f", value)), vjust = 1) +
  scale_fill_gradient(low = "blue", high = "red") +
  theme_bw() + theme(legend.position = "none") + 
  scale_x_discrete(name="Actual Digit", limits=0:9) + scale_y_discrete(name="Predicted Digit", limits=0:9)
```

#Advanced ML Models

##Splitting data train/test
```{r}
data_for_ml = cbind.data.frame(label=mnist.dat$label, scaled_pixels_data)
training_data = sample_n(data_for_ml, prod.sample_size)
validation_data = setdiff(data_for_ml, training_data) 
```

##Tuned
```{r}
tuned_results_multinom <- cv.glmnet(as.matrix(training_data[,-c(1)]), training_data$label,family="multinomial", type.measure="class")
saveRDS(tuned_results_multinom, "tuned_results_multinom.rds")
```

##Tuned
```{r}
tuned_results_svm = tune.svm(label ~., data = training_data, cost=1:5, gamma = 10^seq(-1,-5), tunecontrol=tune.control(cross=prod.number_of_repeats))
saveRDS(tuned_results_svm, "tuned_results_svm.rds")
```

##Tuned
```{r}
copy_for_nn = data.frame(training_data[,-1])
tuned_results_nnet = tune(method=nnet, train.x = class.ind(label) ~ . , data = training_data, MaxNWts=5000, ranges=list(size=seq(1,5), decay=10^seq(-1,-5)), tunecontrol=tune.control(cross=prod.number_of_repeats))
saveRDS(tuned_results_nnet, "tuned_results_nnet.rds")
```

#Plotting Accuracies
```{r}
# png('./figures/accuracies_simple_classifiers.png')
accuracies <- round(accs*100, 2)
par(mar=c(7, 5, 1, 1))
    xx = barplot(accuracies,
    main="Accuracies of different classifiers",
    ylab = "Accuracy (%)",
    ylim=c(0,100), srt=45, xpd=TRUE,
    las=2)
namesss = c("Majority\nclassification", "Density\nonly", "Logarithmic\nnonlinearity", "Edge\ndetection", "First\nprinciple\ncomponent")
text(xx, y = accuracies, label = accuracies, pos = 3, cex = 0.8, col = "red")
axis(1, at=xx, labels=namesss, tick=FALSE, las=2, line=-0.5, cex.axis=1)
# dev.off()
```

```{r}
tuned_results_multinom = readRDS("./tuned_results_multinom.rds")
tuned_results_svm = readRDS("./tuned_results_svm.rds")
tuned_results_nnet = readRDS("./tuned_results_nnet.rds")
```

```{r}
plot(tuned_results_svm)
plot(tuned_results_nnet)
plot(tuned_results_multinom)
```

```{r}
predicted = predict(tuned_results_svm$best.model, validation_data[,-1])
confmat = table(validation_data$label, predicted)
predicted_svm = predicted
plot_confusion_matrix(confmat)
sum(diag(confmat))/sum(confmat)

predicted = predict(tuned_results_nnet$best.model, validation_data[,-1])
predicted = colnames(predicted)[max.col(predicted,ties.method="first")]
confmat = table(validation_data$label, predicted)
predicted_nnet = predicted
plot_confusion_matrix(confmat)
sum(diag(confmat))/sum(confmat)

predicted = predict(tuned_results_multinom, as.matrix(validation_data[,-1]), type="class")
confmat = table(validation_data$label, predicted)
predicted_multinom = predicted
plot_confusion_matrix(confmat)
sum(diag(confmat))/sum(confmat)
```
## McNemar Browker Test
```{r}
mcnemar.test(table(predicted_multinom, predicted_nnet))
mcnemar.test(table(predicted_multinom, predicted_svm))
mcnemar.test(table(as.factor(predicted_nnet), predicted_svm))
```
```{r}
# predicted = predict(tuned_results_nnet$best.model, training_data[,-1])
# predicted = colnames(predicted)[max.col(predicted,ties.method="first")]
# # confmat = table(validation_data$label, predicted)
# # predicted_nnet = predicted
# # plot_confusion_matrix(confmat)
# sum(diag(confmat))/sum(confmat)
```


